services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: '.'
    container_name: frontend-app
    ports:
      - "3000:3000"

  frontend-nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy_frontend
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf